version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    profiles: ["test"]
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${PG_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_USER}

volumes:
  data: {}